Punto3
EspinolaAbel/eis_201802c_tp_grupal pull request #3
Opened 2018-10-15 22:28 UTC by khalilfa

Se termino el punto 3. Se creo una clase Power de la cual descienden los diferentes poderes que existen en el juego.  Esta superclase, al mismo tiempo, extiende de objeto lo cual la hace adquirir todas sus propiedades y métodos. 
  Bomberman solo puede utilizar el el poder si lo tiene almacenado en su lista de poderes y esto lo lleva acabo llamando a un método especifico determinado en su interfaz.

2018-10-16 14:43 UTC, urielintemperie requested changes

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Bagulaa.java
> +        this.alive = false;
Usa this.kill()

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Bomb.java
> +    public void setTicksController(TicksController ticksController) {
Dira de poner un _subscribeTicksController_, que no solo agregue el colaborador interno sino que tambien te subscriba a él ( _tickController.addBomb(this)_ )

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Bomberman.java
>      public void dropBomb(Integer ticks, TicksController ticksController) {
Me suena raro que tenga que recibir por parámetro el _TicksController_ en lugar de que ya lo conozca Bomberman para que así cada vez que tira una bomba le pase siempre este y así todas respondan al mismo _TickController_ por lo que todas las bombas se verían afectadas por el mismo "paso del tiempo"

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Bomberman.java
> +        bomb.setTicksController(ticksController);
Si hacemos el _Bomb.subscribeTicksController()_ acá solo llamaríamos a ese mensaje en lugar de por un lado setearle a la bomba el TicksController y por otro suscribirlo a este

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Bomberman.java
>      public void dropBomb(Integer ticks, TicksController ticksController) {
_dropBomb()_ podría retornar la bomba que creó

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Bomberman.java
> +    public void throwBomb(Integer ticks, TicksController ticksController, Integer cant, Direction direction){
Que _throwBomb_ llame a _dropBomb_ y a la bomba que le retorna le diga _moveXToDir(cant, direction)

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Item.java
> +    private void interact(){
Esto no debería ser responsabilidad del Item sino de Location. Cada vez que se hace _Location.addItem()_ ademas de agregarlo a su set de items tiene que notificarle a los demás para ver si interactuan con él (tal como haces acá). En la forma actual estarías rompiendo el encapsulamiento de Location.

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Item.java
>      public void setCurrentLocation(Location newLocation) {
Falta hacer _newLocation.addItem(this)_

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Location.java
> +    private int yCoord;
¿Por que sacaste los finals? Me sonaba que tenia sentido que Location no pudiera cambiar sus coordenadas ¿Lo necesitabas para un test o algo así?

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/Power.java
> +    protected void interactsWith(Item otherItem) {
Creo que al interactuar con un Bomberman añadiéndose este a sus poderes, debería irse el Power de la Location. Aunque si decís que no porque no te lo pide un caso de uso es entendible.

2018-10-16 14:43 UTC, urielintemperie commented on src/main/java/gradle/cucumber/TicksController.java
> +        this.deleteBombs.add(bomb);
¿Por que hacer que el _removeBomb(Bomb)_ en lugar de directamente eliminarla del set de bombs, se añada a un set de las bombas que serán eliminadas para que luego _tick()_ elimine de bombs todas aquellas que están en el set deleteBombs?¿Por que así y no como ya estaba?

2018-10-16 14:43 UTC, urielintemperie commented on src/test/java/gradle/cucumber/BombermanStepdefs.java
> +    private Direction getDirection(String dir){
¿Por que no hacer _dir.toLowerCase()_ en este método en lugar de que te lo tengan que mandar habiéndole ya aplicado el _toLoweCase()_ como haces en la_boma_se_mueve_celdas_mas_al_que_bomberman(cant, dir)?

2018-10-16 14:43 UTC, urielintemperie commented on src/test/java/gradle/cucumber/BombermanStepdefs.java
> +        assertTrue(!bombLocation.existBomb());
Usa un _assertFalse()_ y no niegues _bombLocation.existBomb()_

2018-10-16 14:43 UTC, urielintemperie commented on src/test/java/gradle/cucumber/BombermanStepdefs.java
> +        assertTrue(!location.existEnemy());
Usa un assertFalse()

2018-10-16 14:43 UTC, urielintemperie commented on src/test/resources/gradle/cucumber/bomberman.feature
> +    Then La pared de acero en x:"2" y:"3" no desaparece por la onda expansiva
En este test entiendo que queres probar que una explosión no afecta a una pared de acero. Pero sucede que Bomberman esta en la posición ( x:0 ; y:0 ) y la pared de acero en ( x:2 ; y:3 ), las explosiones afectan a los casilleros limítrofes "en cruz", no a aquellos que estén en diagonal a la bomba, esa pared no esta en el área de la "onda expansiva"; si queres que lo este ponela en ( x:2 ; y:0 )

2018-10-16 14:43 UTC, urielintemperie commented on src/test/resources/gradle/cucumber/bomberman.feature
> +    Then La bomba se mueve "2" celdas mas al "Norte" que bomberman
Este test esta piola porque muestra que la bomba no se sale de los limites del mapa (porque Bomberman ya esta en ( x:0 ; y: 0) y la tiras hacia el Norte por lo que no se mueve), pero estaría bueno que hubiera otro test en el cual la bomba si se moviera varios casilleros (por ejemplo tirándola al Este)

2018-10-17 18:54 UTC, khalilfa commented on src/main/java/gradle/cucumber/TicksController.java
> +        this.deleteBombs.add(bomb);
Porque estaría eliminando un elemento de un set que sigo recorriendo. Esto genera un error. En cambio, acá genero otro set para mantener los objetos guardados y cuando termina la primera iteracion recién los elimino.

2018-10-21 01:44 UTC, merged